[package]
authors = ["The Veracruz Development Team"]
description = "Samples random data from the trusted Veracruz runtime.  Used to test random number generation in Veracruz."
edition = "2018"
name = "random-source"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.14"
pinecone = { version = "0.2.3", features = ["use-std"] }
rand = "0.8.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
