[package]
authors = ["The Veracruz Development Team"]
description = "A utility for generating synthetic data for use with the `private-set-intersection-sum` example."
edition = "2018"
name = "private-set-intersection-sum-generator"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
postcard = { version = "1.0.0", features = [ "alloc" ] }
rand = "0.8.3"
serde = { version = "1.0.103", features = ["derive"] }
