[package]
name = "sysroot"
version = "0.3.0"
edition = "2018"
authors = ["The Veracruz Development Team"]
description = "Crate that depends on Rust libraries for Icecap"

[dependencies]
std = { path = "../rust/library/std" }

# Hacks to get std to depend on our patches.
libc = "=0.2.144"
# compiler_builtins = "=0.1.69"

[lib]
crate-type = ["rlib"]

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
debug = 0
debug-assertions = true

[patch.crates-io]

rustc-std-workspace-core = { path = "../rust/library/rustc-std-workspace-core" }
rustc-std-workspace-alloc = { path = "../rust/library/rustc-std-workspace-alloc" }
# rustc-std-workspace-std = { path = "../rust/library/rustc-std-workspace-std" }

libc = { path = "../libc" }

icecap-std-impl = { path = "../../icecap/src/rust/crates/framework/std-support/icecap-std-impl" }

[workspace]
resolver = "2"
