[package]
authors = ["The Veracruz Development Team"]
description = "The test program for calling the Darknet inference module."
name = "darknet-inference-native"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.14"
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
serde = { version = "1.0.3", features = ["derive"] }
