[package]
authors = ["The Veracruz Development Team"]
description = "Veracruz integration test.  This is a full system test that should cover all functionality provided by Veracruz."
edition = "2018"
name = "veracruz-test"
version = "0.3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
icecap = [
  "veracruz-client/icecap",
  "veracruz-server/icecap",
  "proxy-attestation-server/icecap",
  "transport-protocol/icecap",
]
linux = [
  "veracruz-client/linux",
  "veracruz-server/linux",
  "proxy-attestation-server/linux"
]
nitro = [
  "veracruz-client/nitro",
  "veracruz-server/nitro",
  "proxy-attestation-server/nitro"
]
sgx = [
  "veracruz-client/sgx",
  "veracruz-server/sgx",
  "sgx_types",
  "sgx_ucrypto",
  "sgx_alloc",
  "proxy-attestation-server/sgx",
  "transport-protocol/sgx_attestation",
]
tz = [
  "veracruz-client/tz",
  "veracruz-server/tz",
  "proxy-attestation-server/tz",
  "transport-protocol/tz"
]

[dependencies]
actix-rt = "1.1.1"
actix-web = "3.3.2"
async-std = "1"
env_logger = "0.7"
err-derive = "0.2"
futures = "0.3"
http = "=0.2.4"
lazy_static = "1.4"
log = "=0.4.13"
pinecone = "0.2"
policy-utils = { path = "../policy-utils", features = ["std"] }
proxy-attestation-server = { path = "../proxy-attestation-server" }
sgx_alloc = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_ucrypto = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
transport-protocol = { path = "../transport-protocol" }
veracruz-client = { path = "../veracruz-client" }
veracruz-server = { path = "../veracruz-server" }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { git = "https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git", branch = "veracruz-v1", optional = true }
sgx_types = { git = "https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git", branch = "veracruz-v1", optional = true }
sgx_ucrypto = { git = "https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git", branch = "veracruz-v1", optional = true }
