[package]
name = "veracruz-test"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Veracruz integration test.  This is a full system test that should cover all functionality provided by Veracruz."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
sgx = ["durango/sgx","sinaloa/sgx", "sgx_types", "sgx_ucrypto", "sgx_alloc", "veracruz-utils/std", "tabasco/sgx", "colima/sgx_attestation"]
tz = ["durango/tz","sinaloa/tz", "veracruz-utils/tz", "tabasco/psa", "colima/tz"]
nitro = ["durango/nitro", "sinaloa/nitro", "veracruz-utils/nitro", "tabasco/nitro"]

[dependencies]
durango = {path = "../durango"}
sinaloa = { path = "../sinaloa"}
veracruz-utils = { path = "../veracruz-utils", features = ["std"] }
serde_json = "1.0"
serde = { version = "1.0.97", features = ["derive"] }
tabasco = { path = "../tabasco"}
colima = { path = "../colima"}
hex = "0.3.1"
ring = "0.16.5"
actix-rt = "1.0.0"
actix-web = "2.0.0"
futures = "0.3"
async-std = "1"
pinecone = "0.2"
env_logger = "0.7"
log = "0.4"
lazy_static = "1.4"
err-derive = "0.2"

[target.'cfg(target_arch = "x86_64")'.dependencies]
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_ucrypto = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_alloc = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_ucrypto = { git = "https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git", branch="veracruz", optional = true }
sgx_types = { git = "https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git", branch="veracruz", optional = true }
sgx_alloc = { git = "https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git", branch="veracruz", optional = true }

