[package]
name = "veracruz-test"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Veracruz integration test.  This is a full system test that should cover all functionality provided by Veracruz."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
sgx = ["veracruz-client/sgx","veracruz-server/sgx", "sgx_types", "sgx_ucrypto", "sgx_alloc", "veracruz-utils/std", "proxy-attestation-server/sgx", "transport-protocol/sgx_attestation"]
tz = ["veracruz-client/tz","veracruz-server/tz", "veracruz-utils/tz", "proxy-attestation-server/psa", "transport-protocol/tz"]
nitro = ["veracruz-client/nitro", "veracruz-server/nitro", "veracruz-utils/nitro", "proxy-attestation-server/nitro"]
icecap = ["veracruz-client/icecap", "veracruz-server/icecap", "veracruz-utils/icecap", "proxy-attestation-server/psa", "transport-protocol/icecap"]

[dependencies]
veracruz-client = {path = "../veracruz-client"}
veracruz-server = { path = "../veracruz-server"}
veracruz-utils = { path = "../veracruz-utils", features = ["std"] }
serde_json = "1.0"
serde = { version = "1.0.97", features = ["derive"] }
proxy-attestation-server = { path = "../proxy-attestation-server"}
transport-protocol = { path = "../transport-protocol"}
hex = "=0.4.2"
http = "=0.2.4"
ring = "0.16.5"
actix-rt = "1.1.1"
actix-web = "3.3.2"
futures = "0.3"
async-std = "1"
pinecone = "0.2"
env_logger = "0.7"
log = "=0.4.13"
lazy_static = "1.4"
err-derive = "0.2"
local_ipaddress = "0.1.3"
regex = "1.4"
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_ucrypto = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_alloc = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_ucrypto = { git = "https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git", branch="veracruz", optional = true }
sgx_types = { git = "https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git", branch="veracruz", optional = true }
sgx_alloc = { git = "https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git", branch="veracruz", optional = true }

