[package]
authors = ["The Veracruz Development Team"]
description = "Generates Veracruz policy files from a set of command line parameters."
edition = "2018"
name = "generate-policy"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
clap = "2.33.3"
data-encoding = "2.3.2"
env_logger = "0.8.2"
log = "=0.4.13"
policy-utils = { path = "../../policy-utils", features = ["std"] }
ring = "0.16.11"
serde = { version = "1.0.115", features = ["std"] }
serde_json = { version = "1.0", features = ["std"] }
veracruz-utils = {path = "../../veracruz-utils", features = ["std"]}
wasi-types = { git = "https://github.com/mathias-arm/wasi-types.git", branch = "veracruz" }
