[package]
name = "generate-policy"
version = "0.1.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Generates Veracruz policy files from a set of command line parameters."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "=1.2.1"
chrono = "0.4.19"
clap = "2.33.3"
data-encoding = "2.3.2"
env_logger = "0.8.2"
log = "0.4.14"
ring = { git = "https://github.com/veracruz-project/ring.git", branch = "veracruz", features = ["non_sgx"] }
veracruz-utils = {path = "../../veracruz-utils", features = ["std"]}
serde = { git = "https://github.com/veracruz-project/serde.git", branch = "veracruz", features = ["std"] }
serde_json = { git = "https://github.com/veracruz-project/json.git", branch = "veracruz", features = ["std"] }
wasi-types = { git = "https://github.com/veracruz-project/wasi-types.git", branch = "veracruz", features = ['std'] }
