[package]
name = "durango"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Client code for provisioning secrets into, and otherwise interacting with, the trusted Veracruz runtime"

[features]
sgx = ["sgx_types", "sgx_ucrypto", "transport-protocol/sgx_attestation"]
tz = []
nitro = []
mock = ["mockall", "mockito"]

[dependencies]
# The cargo patch mechanism does NOT work when we add function into a macro_rules!
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz" }
webpki = { git = "https://github.com/veracruz-project/webpki.git", branch = "veracruz" }

webpki-roots = { git = "https://github.com/veracruz-project/webpki-roots.git", branch = "veracruz"}
ring = { git = "https://github.com/veracruz-project/ring.git", branch = "veracruz"}
reqwest = { version = "0.9", default-features=false }
transport-protocol = { path = "../transport-protocol" }
base64 = "0.10.1"
rand = "0.7.0"
x509-parser="0.6.0"
curl = "0.4.22"
veracruz-utils = { path = "../veracruz-utils", features = ["std"] }
hex = "=0.4.2"
percent-encoding = "2.1.0"
serde_json = { git = "https://github.com/veracruz-project/json.git", branch = "veracruz" }
stringreader = "0.1.1"
err-derive = "0.2"

# Used in unit tests. Mock all the network traffic
mockall = { version = "0.5.0", optional = true }
mockito = { version = "0.23.1", optional = true } 

[target.'cfg(target_arch = "x86_64")'.dependencies]
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_ucrypto = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_ucrypto = { branch="veracruz", git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', optional = true }
sgx_types = { branch="veracruz", git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', optional = true }  

[dev-dependencies]
actix-web = "2.0.0"
futures = "0.3"
actix-rt = "1.0.0"
actix-session = "0.3.0"
actix-http = "1.0.1"

[patch.crates-io]
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "self_signed" }
