[package]
authors = ["The Veracruz Development Team"]
description = "An untrusted server/bridge that allows the outside world and the trusted Veracruz runtime to communicate with each other."
edition = "2018"
name = "veracruz-server"
version = "0.3.0"

[[bin]]
name = "veracruz-server"
path = "src/cli.rs"
required-features = ["cli"]

[features]
# a feature to enable CLI-only dependencies
# https://stackoverflow.com/questions/35711044/how-can-i-specify-binary-only-dependencies
cli = [
  "env_logger",
  "policy-utils/std",
  "structopt",
]
debug = []
icecap = [
  "io-utils/icecap",
  "policy-utils/icecap",
  "psa-attestation",
  "signal-hook",
  "tempfile",
  "veracruz-utils/icecap",
]
icecap-lkvm = []
icecap-qemu = []
linux = [
  "data-encoding",
  "io-utils/linux",
  "nix",
  "policy-utils/std",
  "tempfile",
  "veracruz-utils/linux",
]
nitro = [
  "io-utils/nitro",
  "nitro-enclave",
  "nix",
  "policy-utils/std",
  "veracruz-utils/nitro",
]

[dependencies]
anyhow = "1"
base64 = "0.13.0"
bincode = { version = "1.2.1", default-features = false }
data-encoding = { version = "2.3.2", optional = true }
env_logger = { version = "0.9.0", optional = true }
err-derive = "0.2"
hex = "0.4.2"
io-utils = { path = "../io-utils", optional = true }
lazy_static = "1.4"
log = "0.4.13"
nitro-enclave = { git = "https://github.com/veracruz-project/nitro-enclave", tag = "v0.1", optional = true}
nix = { version = "0.20.2", optional = true }
postcard = "0.7.2"
policy-utils = { path = "../policy-utils", optional = true }
proxy-attestation-client = { git = "https://github.com/veracruz-project/proxy-attestation-client", tag = "v0.2" }
psa-attestation = { path = "../psa-attestation", optional = true }
rand = "0.8.3"
reqwest = { version = "0.11", default-features = false, features = ["blocking", "multipart", "rustls-tls"] }
serde = { version = "1.0.115", default-features = false, features = ["derive"] }
serde_json = "1.0"
signal-hook = { version = "0.3.13", optional = true }
structopt = { version = "0.3", optional = true, features = ["wrap_help"] }
tempfile = { version = "3.2.0", optional = true }
transport-protocol = { path = "../transport-protocol" }
uuid = { version = "1.1.2", features = ["serde"] }
veracruz-utils = { path = "../veracruz-utils", optional = true }
