[package]
authors = ["The Veracruz Development Team"]
description = "TLS endpoint and session management for the trusted Veracruz runtime"
edition = "2018"
name = "session-manager"
version = "0.3.0"

[features]
icecap = [
  "policy-utils/icecap",
  "ring/std",
]
nitro = [
  "policy-utils/std",
  "ring/std",
]
std = [
  "policy-utils/std",
  "ring/std",
]

[dependencies]
err-derive = "0.2"
policy-utils = { path = "../policy-utils" }
ring = "0.16.11"
rustls = "0.20.4"
rustls-pemfile = "0.3.0"
veracruz-utils = { path = "../veracruz-utils" }
webpki = "=0.22"
webpki-roots = "0.22"
