[package]
name = "session-manager"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "TLS endpoint and session management for the trusted Veracruz runtime"

[features]
sgx = ["veracruz-utils/sgx", "sgx_tstd", "sgx_types", "rustls/mesalock_sgx", "webpki/mesalock_sgx", "ring/mesalock_sgx", "webpki-roots/mesalock_sgx"] 
# NOTE: turn on the `std` on ring for Error trait
tz = ["veracruz-utils/tz", "webpki/default", "webpki-roots/default", "ring/std", "ring/non_sgx", "optee-utee", "rustls/default"]
nitro = ["ring/std", "ring/non_sgx"]
icecap = ["veracruz-utils/icecap", "ring/std", "ring/non_sgx"]
std = ["veracruz-utils/std", "ring/std"]

[dependencies]
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz" }
ring = { git = "https://github.com/veracruz-project/ring.git", branch = "veracruz" }
veracruz-utils = { path = "../veracruz-utils" }
webpki = { git = "https://github.com/veracruz-project/webpki.git", branch = "veracruz" }
webpki-roots = { git = "https://github.com/veracruz-project/webpki-roots.git" , branch = "veracruz"}
err-derive = "0.2"
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
optee-utee = { git = "https://github.com/veracruz-project/rust-optee-trustzone-sdk.git", branch = "veracruz", optional = true }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { branch="veracruz", git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', optional = true }
