[package]
name = "random-u32-list"
authors = ["The Veracruz Development Team"]
description = "Samples 32 random u32 numbers and output as a comma-seperated string."
version = "0.3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.14"
rand = "0.8.3"
