[package]
authors = ["The Veracruz Development Team"]
description = "A utility for generating synthetic datasets for use with the `intersection-set-sum` example."
edition = "2018"
name = "intersection-set-sum-generator"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
postcard = { version = "0.7.2", features = [ "alloc", "use-std" ] }
rand = "0.7"
