[package]
name = "veracruz-utils"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Miscellaneous and common code used by multiple Veracruz components.  (A utility library.)"

[features]

sgx = ["sgx_tstd", "serde/mesalock_sgx", "serde_json/mesalock_sgx", "serde_json/alloc", "ring/mesalock_sgx"]
tz = ["serde_json/std", "ring"]
std = ["serde/std", "rustls","serde_json/std", "ring"]
nitro = ["serde_json/std", "nix", "byteorder", "ring/non_sgx"]
icecap = ["ring"]

[dependencies]
sgx_tstd = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
serde = { git = "https://github.com/veracruz-project/serde.git", features=["derive"], branch = "veracruz" }
serde_json = { git = "https://github.com/veracruz-project/json.git", branch = "veracruz", default-features = false }
# The cargo patch mechanism does NOT work when we add function into a macro_rules!
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz", optional = true }
err-derive = "0.2"
nix = { version = "0.15", optional = true }
byteorder = { version = "1.3", optional = true }
ring = { git = "https://github.com/veracruz-project/ring.git", version = "=0.16.11", branch = "veracruz", optional = true }

backtrace = "=0.3.61"
http = "=0.2.4"

[build-dependencies]
uuid = { version = "0.7", features = ["v4"] }

[patch.crates-io]
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "self_signed", optional = true }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_alloc = { branch="veracruz", git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', optional = true }
