[package]
authors = ["The Veracruz Development Team"]
description = "Miscellaneous and common code used by multiple Veracruz components.  (A utility library.)"
edition = "2018"
name = "veracruz-utils"
version = "0.3.0"

[features]
icecap = [
  "platform-services/icecap",
  "serde/derive",
]
linux = [
  "platform-services/std",
  "serde/derive",
  "serde_json/std",
]
nitro = [
  "platform-services/nitro",
  "serde/derive",
  "serde_json/std",
]
std = [
  "platform-services/std",
  "serde/std",
  "serde_json/std",
]

[dependencies]
anyhow = "1"
bincode = { version = "1.2.1", default-features = false, optional = true }
err-derive = "0.2"
mbedtls = { path = "../third-party/rust-mbedtls/mbedtls" }
platform-services = { path = "../platform-services" }
psa-crypto = { path = "../third-party/rust-psa-crypto/psa-crypto" }
# The cargo patch mechanism does NOT work when we add function into a macro_rules!
serde = { version = "1.0.115", default-features = false, optional = true }
serde_json = { version = "1.0", default-features = false }
x509-parser = { version = "0.13.0", optional = true }
