[package]
authors = ["The Veracruz Development Team"]
description = "Miscellaneous and common code used by multiple Veracruz components.  (A utility library.)"
edition = "2018"
name = "veracruz-utils"
version = "0.3.0"

[features]
linux = [
  "platform-services/std",
  "serde/derive",
  "serde_json/std",
]
nitro = [
  "mbedtls/monitor_getrandom",
  "platform-services/nitro",
  "serde/derive",
  "serde_json/std",
]
std = [
  "chrono",
  "platform-services/std",
  "serde/std",
  "serde_json/std",
]

[dependencies]
anyhow = "1"
bincode = { version = "1.2.1", default-features = false, optional = true }
chrono = { version = "0.4.19", default-features = false, features = ["clock", "std"], optional = true }
err-derive = "0.2"
mbedtls = { path = "../third-party/rust-mbedtls/mbedtls", default-features = false, features = ["std", "aesni", "padlock", "tls13"] }
platform-services = { path = "../platform-services", optional = true }
# The cargo patch mechanism does NOT work when we add function into a macro_rules!
serde = { version = "1.0.115", default-features = false, optional = true }
serde_json = { version = "1.0", default-features = false }
uuid = { version = "1.1.2", features = ["serde"] }
