[package]
authors = ["The Veracruz Development Team"]
description = "Miscellaneous and common code used by multiple Veracruz components.  (A utility library.)"
edition = "2018"
name = "veracruz-utils"
version = "0.3.0"

[features]
icecap = [
  "ring/non_sgx",
  "serde/derive",
]
linux = [
  "ring/non_sgx",
  "serde/derive",
  "serde_json/std",
]
nitro = [
  "ring/non_sgx",
  "serde/derive",
  "serde_json/std",
]
std = [
  "ring/std",
  "rustls",
  "serde/std",
  "serde_json/std",
]

[dependencies]
err-derive = "0.2"
ring = "0.16.11"
# The cargo patch mechanism does NOT work when we add function into a macro_rules!
rustls = "0.16"
serde = { git = "https://github.com/veracruz-project/serde.git", default-features = false, branch = "veracruz", optional = true }
serde_json = { git = "https://github.com/veracruz-project/json.git", branch = "veracruz", default-features = false }
webpki = "=0.21.2"

[patch.crates-io]
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "self_signed", optional = true }
