[package]
name = "veracruz-server-test"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Veracruz integration test-suite.  Tests trusted Veracruz runtime functioanlity, and session management code, without establishing a network connection."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
sgx = ["sgx_ucrypto", "sgx_urts", "sgx_types", "veracruz-server/sgx","veracruz-utils/std", "proxy-attestation-server/sgx", "transport-protocol/sgx_attestation", "psa-attestation/sgx"]
tz = ["veracruz-server/tz", "veracruz-utils/tz", "proxy-attestation-server/tz", "transport-protocol/tz", "psa-attestation/tz"]
nitro = ["veracruz-server/nitro", "veracruz-utils/nitro", "proxy-attestation-server/nitro"]
icecap = ["veracruz-server/icecap", "veracruz-utils/icecap", "proxy-attestation-server/icecap"]
# debug feature means the enclaves will be started in debug mode (when available)
# which changes behaviors depending on the platform (for example in Debug mode,
# Nitro enclave attestation documents have the PCRs zeroed out and the console
# cannot connect)
debug = ["veracruz-server/debug"]

[dependencies]
veracruz-server = { path = "../veracruz-server"}
veracruz-utils = { path = "../veracruz-utils", features=["std"] }
webpki = { git = "https://github.com/veracruz-project/webpki.git", branch = "veracruz" }
webpki-roots = { git = "https://github.com/veracruz-project/webpki-roots.git", branch = "veracruz" }
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz" }
ring = { git = "https://github.com/veracruz-project/ring.git", branch = "veracruz" }
transport-protocol = { path = "../transport-protocol" }
protobuf = "2.6"
curl = "=0.4.35"
untrusted = "0.6.2"
base64 = "0.10.1"
stringreader = "0.1.1"
serde_json = "1.0"
serde = { version = "1.0.97", features = ["derive"] }
percent-encoding = "2.1.0"
openssl = "0.10.24"
rand = "0.7.0"
proxy-attestation-server = { path = "../proxy-attestation-server" }
psa-attestation = { path = "../psa-attestation"}
hex = "=0.4.2"
http = "=0.2.4"
pinecone = "0.2"
futures = "0.3"
actix-rt = "1.1.1"
env_logger = "0.7"
log = "=0.4.13"
lazy_static = "1.4"
regex = "1.4"
local_ipaddress = "0.1.3"
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_ucrypto = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_urts = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_ucrypto = { branch="veracruz", git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', optional = true }
sgx_types = { branch="veracruz", git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', optional = true }
sgx_alloc = { branch="veracruz", git = 'https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git', optional = true }

[patch.crates-io]
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz" }


