[package]
authors = ["The Veracruz Development Team"]
description = "Generates Veracruz policy files from a set of command line parameters."
edition = "2018"
name = "generate-policy"
version = "0.1.0"

[dependencies]
anyhow = "1"
chrono = { version = "0.4.19", default-features = false, features = ["clock", "std"] }
clap = "2.33.3"
data-encoding = "2.3.2"
env_logger = "0.10.0"
log = "0.4.13"
policy-utils = { path = "../../policy-utils", features = ["std"] }
regex = "1.5.5"
serde = { version = "1.0.115", features = ["std"] }
serde_json = { version = "1.0", features = ["std"] }
veracruz-utils = { path = "../../veracruz-utils", features = ["std"] }
wasi-types = { path = "../../third-party/wasi-types" }
