[package]
authors = ["The Veracruz Development Team"]
description = "A utility for generating a postard encode of a made-up type."
edition = "2018"
name = "postcard-generator"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
postcard = { version = "1.0.0", features = [ "alloc" ] }
serde = { version = "1.0.3", features = ["derive"] }
rand = "0.8.3"
