[package]
name = "csv-encoder"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "A utility for encoding CSV-structured data into the binary `pinecone` format.  Provides means of selecting columns and skipping incomplete rows."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags   = "=1.2.1"
clap       = "2.33.0"
csv        = "1.0"
env_logger = "0.7.1"
log        = "0.4.8"
pinecone   = "*"
serde      = { version = "1.0.103", features = ["derive"] }
toml       = "0.5.6"

[profile.release]
lto           = true
codegen-units = 1
opt-level     = 3

