[package]
authors = ["Shale Xiong <shale.xiong@arm.com>"]
description = "A utility for generating synthetic datasets for use with the `linear-regression` example."
edition = "2018"
name = "linear-regression-generator"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
postcard = { version = "1.0.0", features = [ "alloc" ] }
rand = "0.8.3"
rand_distr = "0.4"
