plugin:
  backend: go-plugin
  go-plugin:
    dir: ./plugins/
ta-store:
  backend: memory
en-store:
  backend: memory
po-store:
  backend: memory
po-agent:
  backend: opa
vts:
  server-addr: 127.0.0.1:50051
ear-signer:
  alg: ES256
  key: ./skey.jwk
logging:
  level: debug
