[package]
authors = ["The Veracruz Development Team"]
description = "A utility for geneting synthetic datasets for use with the `private-set-intersection` example."
edition = "2018"
name = "private-set-intersection-generator"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
csv = "1.0"
postcard = { version = "1.0.0", features = [ "alloc" ] }
serde = { version = "1.0.103", features = ["derive"] }
