[package]
name = "sinaloa"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "An untrusted server/bridge that allows the outside world and the trusted Veracruz runtime to communicate with each other."

[features]
sgx = ["veracruz-utils/std","sgx_types", "sgx_urts", "transport-protocol/sgx_attestation", "mexico-city-bind", "trustzone-root-enclave-bind"]
tz = ["veracruz-utils/std", "veracruz-utils/tz", "transport-protocol/tz", "optee-teec", "uuid"]
nitro = ["veracruz-utils/nitro", "bincode", "serde/derive", "byteorder", "nix", "ssh2" ]
debug = []

[dependencies]
dirs = "1.0.2"
veracruz-utils = { path = "../veracruz-utils", features = ["std","tz"] }
serde_json = { git = "https://github.com/veracruz-project/json.git", branch = "veracruz" }
transport-protocol = { path = "../transport-protocol"}
rouille = "3.0"
base64 = "0.10.1"
untrusted = "0.6.2"
ring = "0.16"
stringreader = "0.1"
curl = "0.4"
lazy_static = "1.4"
actix-web = "2.0.0"
actix-http = "1.0"
futures = "0.3"
log = "0.4"
err-derive = "0.2"
pinecone = "0.2"
hex = "=0.4.2"
webpki = { git = "https://github.com/veracruz-project/webpki.git", branch = "veracruz" }
rustls = { git = "https://github.com/veracruz-project/rustls.git", branch = "veracruz" }
bincode = { git = "https://github.com/veracruz-project/bincode.git", branch = "veracruz", default-features = false, optional = true }
serde = { git = "https://github.com/veracruz-project/serde.git", default-features = false, optional = true }
byteorder = { version = "1.3.2", optional = true }
nix = { version = "0.15", optional = true }
ssh2 = {version = "0.8.3", optional = true }

[target.'cfg(target_arch = "x86_64")'.dependencies]
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_urts = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
mexico-city-bind = { path = "../mexico-city-bind", optional = true }
trustzone-root-enclave-bind = { path = "../trustzone-root-enclave-bind", optional = true }

[target.'cfg(target_arch = "aarch64")'.dependencies]
optee-teec = { git = "https://github.com/veracruz-project/rust-optee-trustzone-sdk.git", branch = "veracruz", optional = true }
# for the error handling 
uuid = { version = "0.7", optional = true }
hex = {version = "=0.4.2", optional = true }

[build-dependencies]
target_build_utils = "0.1"
