[package]
name = "sinaloa"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "An untrusted server/bridge that allows the outside world and the trusted Veracruz runtime to communicate with each other."

[features]
sgx = ["veracruz-utils/std","sgx_types", "sgx_urts", "colima/sgx_attestation", "mexico-city-bind", "sonora-bind"]
tz = ["veracruz-utils/std", "veracruz-utils/tz", "colima/tz", "optee-teec", "uuid"]

[dependencies]
dirs = "1.0.2"
veracruz-utils = { path = "../veracruz-utils", features = ["std","tz"] }
serde_json = { git = "https://github.com/veracruz-project/json.git", branch = "veracruz" }
colima = { path = "../colima"}
rouille = "3.0"
base64 = "0.10.1"
untrusted = "0.6.2"
ring = "0.16"
stringreader = "0.1"
curl = "0.4"
lazy_static = "1.4"
mexico-city-bind = { path = "../mexico-city-bind" }
sonora-bind = { path = "../sonora-bind" }
actix-web = "2.0.0"
actix-http = "1.0"
futures = "0.3"
log = "0.4"
err-derive = "0.2"
pinecone = "0.2"
hex = "0.4"
webpki = "0.21.0"
rustls = "0.16.0"

[target.'cfg(target_arch = "x86_64")'.dependencies]
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_urts = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
mexico-city-bind = { path = "../mexico-city-bind", optional = true }
sonora-bind = { path = "../sonora-bind", optional = true }

[target.'cfg(target_arch = "aarch64")'.dependencies]
optee-teec = { git = "https://github.com/veracruz-project/rust-optee-trustzone-sdk.git", branch = "veracruz", optional = true }
# for the error handling 
uuid = { version = "0.7", optional = true }
hex = {version = "0.4", optional = true }

[build-dependencies]
target_build_utils = "0.1"
