[package]
authors = ["The Veracruz Development Team"]
description = "A freestanding WASM execution engine implementing the Veracruz ABI for offline development and testing."
edition = "2018"
name = "freestanding-execution-engine"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "=1.2.1"
clap = "2.33.3"
env_logger = "0.7.1"
execution-engine = { path = "../../execution-engine", features = ["std"] }
http = "=0.2.4"
log = "=0.4.13"
pinecone = "0.2.3"
policy-utils = { path = "../../policy-utils", features = ["std"] }
serde = { version = "1.0.103", features = ["derive"] }
toml = "0.5.5"
wasi-types = { git = "https://github.com/veracruz-project/wasi-types.git", branch = "veracruz" }
wast = "=35.0.0"
wat = "<1.0.38"

[[bin]]
name = "freestanding-execution-engine"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
