[package]
name = "freestanding-execution-engine"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "A freestanding WASM execution engine implementing the Veracruz ABI for offline development and testing."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
execution-engine = { path = "../../execution-engine", features = ["std"] }
veracruz-utils = { path = "../../veracruz-utils", features = ["std"] }
clap = "2.33.3"
bitflags = "=1.2.1"
env_logger = "0.7.1"
log = "0.4.8"
serde = { version = "1.0.103", features = ["derive"] }
toml = "0.5.5"
wast = "=35.0.0"
wat = "<1.0.38"
wasi-types = { git = "https://github.com/veracruz-project/wasi-types.git", branch = "veracruz" }

[[bin]]
name = "freestanding-execution-engine"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
