[package]
authors = ["The Veracruz Development Team"]
description = "Moving the cursor of a text file for forward for a number of bytes, read the remaining bytes and write it into a text file"
name = "file-seek"
version = "0.3.0"
edition = "2018"

[dependencies]
anyhow = "1.0.14"
