[package]
authors = ["The Veracruz Development Team"]
description = "A utility for generating synthetic datasets for use with the `moving-average-convergence-divergence` example."
edition = "2018"
name = "moving-average-convergence-divergence-generator"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
csv = "1.0"
postcard = { version = "0.7.2", features = [ "alloc" ] }
rand = "0.7"
rand_distr = "0.3"
