[package]
name = "tabasco"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
build = "build.rs"
description = "The Veracruz attestation web-service.  Maintains a database of enrolled isolates.  Can be used to authenticate or reject attestation tokens purporting to originate from these isolates."

[[bin]]
name = "tabasco_bin"
path = "src/main.rs"

[lib]
crate-type =["lib"]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# a feature to enable SGX native attestation. Only available on x64 platforms
sgx = ["sgx_types", "sgx_ucrypto", "sgx_urts", "psa-attestation/sgx", "colima/sgx_attestation"]

# a feature to enable PSA native attestation.
# Note: Final attestation is always PSA. This is just to enable platforms
# that use PSA for their native attestation.
psa = ["psa-attestation/tz"]
nitro = []

[dependencies]
rouille = "3.0"
lazy_static = "1.3"
base64 = "0.10"
colima = { path = "../colima" }
curl = "0.4"
rand = "0.7"
stringreader = "0.1"
percent-encoding = "2.1"
openssl = "0.10.24"
serde_json = "1.0"
diesel = { version = "1.0.0", features = ["sqlite", "numeric" ] }
dotenv = "0.9.0"
hex = "0.3"
psa-attestation = { path = "../psa-attestation" }
ring = "0.16"
futures = "0.3"
veracruz-utils = { path = "../veracruz-utils", features = ["std"] }
actix-web = "2.0.0"
actix-rt = "1.0.0"
actix-http = "1.0"
async-std = "1.5"
env_logger = "0.7"
err-derive = "0.2"

[target.'cfg(target_arch = "x86_64")'.dependencies]
sgx_types = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_ucrypto = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }
sgx_urts = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git", optional = true }

[dev-dependencies]
sgx_urts = { rev = "v1.1.2", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sonora-bind = { path = "../sonora-bind" }
psa-attestation = { path = "../psa-attestation" }

[patch."https://github.com/apache/teaclave-sgx-sdk.git"]
sgx_ucrypto = { git = "https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git", branch="veracruz",  optional = true }
sgx_types = { git = "https://github.com/veracruz-project/incubator-teaclave-sgx-sdk.git", branch="veracruz",  optional = true }
