
[package]
authors = ["Shale Xiong"]
edition = "2018"
name = "veracruz-server-fuzz"
publish = false
version = "0.0.0"

[package.metadata]
cargo-fuzz = true

# Has to use 0.1.1 due to any later versions import arbitrary packages
# that are incompatable with the rust version we are using.
[dependencies]
libfuzzer-sys = "=0.1.1"
protobuf = "=2.6.2"
ring = "0.14.6"
rustls = { path = "../../third-party/rustls" }
serde_json = "1.0"
transport-protocol = { path = "../../transport-protocol_std" }
veracruz_utils = { path = "../../veracruz_utils_std" }
webpki = "0.19"
webpki-roots = "0.16"

[dependencies.veracruz-server]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "provision_data"
path = "fuzz_targets/provision_data.rs"
