[package]
authors = ["The Veracruz Development Team"]
description = "A utility for generating synthetic datasets for use with the `idash2017-logistic-regression` example."
edition = "2018"
name = "idash2017-logistic-regression-generator"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "=1.2.1"
clap = "2.33"
csv = "1.0"
pinecone = "0.2"
rand = "0.7"
rand_distr = "0.3"
serde = { version = "1.0.103", features = ["derive"] }
