[package]
authors = ["The Veracruz Development Team"]
description = "A utility for generating synthetic datasets for use with the `idash2017-logistic-regression` example."
edition = "2018"
name = "idash2017-logistic-regression-generator"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
csv = "1.0"
postcard = { version = "1.0.0", features = [ "alloc" ] }
rand = "0.8.3"
rand_distr = "0.4"
