[package]
authors = ["The Veracruz Development Team"]
description = "A utility for generating synthetic images for use with the `image-processing` example."
edition = "2018"
name = "image-processing-generator"
version = "0.1.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4"
image = "0.23.14"
