[package]
authors = ["The Veracruz Development Team"]
build = "build.rs"
description = "An implementation of Arm's PSA attestation protocol."
edition = "2018"
links = "psa_attestation"
name = "psa-attestation"
version = "0.3.0"

[lib]
crate-type = ["rlib"]

[features]
# build.rs depends on features
icecap = []
linux = []
nitro = []

[dependencies]
libc = "0.2.69"
# We are not really using psa-crypto but we are using the C libraries
# libmbedcrypto.a and libshim.a that psa-crypto indirectly uses.
psa-crypto = { path = "../third-party/rust-psa-crypto/psa-crypto" }

[build-dependencies]
bindgen = "0.57.0"
cfg-if = "1.0"
cmake = "0.1"
