[package]
authors = ["The Veracruz Development Team"]
build = "build.rs"
description = "An implementation of Arm's PSA attestation protocol."
edition = "2018"
links = "psa_attestation"
name = "psa-attestation"
version = "0.3.0"

[lib]
crate-type = ["rlib"]

[features]
# build.rs depends on features
icecap = []
linux = []
nitro = []

[dependencies]
libc = "0.2.69"

[build-dependencies]
bindgen = "0.53.1"
cfg-if = "1.0"
cmake = "0.1"
