[package]
authors = ["The Veracruz Development Team"]
description = "A utility for generating synthetic 3 data files: *-init.dat containing a single 64-bit floating point number, and *-1.dat and *-2.dat which are two Vecs of 64-bit floating point numbers respectively."
edition = "2018"
name = "number-stream-generator"
version = "0.3.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
postcard = { version = "1.0.0", features = [ "alloc", "use-std" ] }
rand = "0.8.3"
rand_distr = "0.4"
